language: node_js

node_js:
  - 'stable'
  - '4'
  - '5'

sudo: false

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - npm install -g codeclimate-test-reporter

script:
  - npm run build
  - npm run validate

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
  - node_modules/.bin/coveralls < coverage/lcov.info

before_deploy:
  - npm run build:dist && node ./script/package-dist.js

deploy:
  - provider: npm
    email: 'devmonk@mediamonks.com'
    api_key:
      secure: 'chXXBVpahYwvPQqE+iv4owKeVZ7PJvWLDz4+ArbiiwJuz203Y0a6lEOvw4o7gnVIy1xUYpT2tfNB6vUKV2u9KW1LtRTDI2J55nX+kpWGLj37hrbMfKkNNTS5fE0pFr5urIz650Ofa8BPfnc47LRZuRHWPE0bRaGge2eUNexjWAItiXOWEySwPYv38XxxCKndgFFHt33TXZTonlmFbYczUIb/QIkp/XPW9OYCrFfP84vKUF6lD0cULkrTeVg3ez/JhT6oqpTERwhG3aKy0nzsNOsse4HQfob7g82ZqzWaxGQIQVXV93AkLGKLJbeIkCyIEJjK+Z7A1Vjh2tLWQQZly0CZyqBfBVamNur7oXJuYQnJe+Y0TAIJ2FQfWDMFS2i+dnWfmT7LPwTIl3NQyCMNx41nRpCyGEJXncA807HslfGPbLsqmmx/Efg/xQF4gl9RH34C0zY5NkJ0yKnb4R3r4ZOtSJiF/O4ndTxmVJp1bC5mGW6/aYlSli8llzC/1AbPEqs0IgMzIPnjdtUvNsmELm4dfzrIB6xBoafZuumxyzOqf9xn2hZHFRwF4AHEGw/+eVQUCs+qCkn4fVzvaYkhkT7tzGo8f8xhh7SViZuWjb0plC6QrSjRU+u4PxqwroVvah52o2sLY8zayZpUFGd5CydNG6MdAhW68eCiUx5cuOg'
    on:
      tags: true
      node: '4'
    skip_cleanup: true

  - provider: releases
    api_key:
      secure: 'ahH+HZuXibkorBAflGeMNpxYEt2JHJ+z7t+ydktQZ8Umqn+dOEubTNZNqp4kmLC8lKD/EAPggSQGuRob9zP/m9tZGMnrqfy+RpokYP0OkVJnxW9NeMNBFMshTrxgH8CecHsJU59zrSUqRJA4EJkisQCQPj+i3go/xIVIOe0gYPxzNdobj5cuMQCahaMTHAkBACNcdkMkoo0Sg6+0pf4O/mG2g2sWYk3E4je8IVQkXTVsc/72TcRWBWRFsUlO8yLWp6DvgEZjC9fl28EvJTitIYCdIibhvrGnm4kl6jjIYrZ7cqXaPDnBL7vm+TQCfitg58OFgm+SsVU36lEIjT0IMMZm9lwPIA71K+OirnYw51lL6AibYuN2krfCWYNA8HT8O6D9g5DLFDfyqK1iQmZv0KXKjL2bdhluG+KT6jKGq1A9WgybcA2+0y6/lR5pXaMCRwM5fH4Fwf5IJtUz5H/3fFt1fHkYZ+y565E5ObS8TsutqrMzuwDZehQcr9OABRgkdEyETziW6FFD1Sq22PMZzLPR/tXDz5Uf4gu2iO/T0hxK6gtACTT/L+7UY7wG12xQqkMPd/k9fiwjnd3RWBAwweI1BId/xEPIUS1Vj/obTimCg3wnVpyH4nJyZ78U4guNfp+A9d67y04F8kPwq6rrSLYhtpaKkEj2TZsv8ACSMPM='
    file:
      - "seng-*.zip"
      - "seng-*.tar.gz"
    file_glob: true
    on:
      tags: true
      node: '4'
    skip_cleanup: true

addons:
  code_climate:
    repo_token:
      secure: 'jMib2LNFGzfKiINRK0fOwibNgHnizTh87Fb1YK0Q2UpWtF7WiigEBhNyiX3pF02HH3iRuICHKYzE1QrZbIzk88XVTUhilO7vI+h1VpgbcuOxq7nkE+kSfxAiTpkD6eY7c0s8wSViKTPOVPPrpRfp8RYYLx6Vcox9jlN7StOHAgDuiwGwHPZ6lz2KGzX1xx8Z8ZLnHIIihv7rqQgetu7BNoPcrPv2Dz63qZI3DbFPWVJIe05B6I7iuiPgzlRZzIvUWofpp6zM5jT9ktrGyF786sh15mDzixoDzUDKmw6ptbc7MeoEuT2Co7FYr4LibXClSaoXcfKJ37/6E5Xzya1e7Sz/83+H1Xi34LCUcVHySzmCWSMWa1fGnZMCHJUdhCVmY5EJMQSGJEvPwHt+1beRYsWAm0cP2RsZ3LhIj9uB6jVXUz1pmhlkL2AFiuBZ2D3vKw4DTtnKqBounsI/FFm0Z0bhsOfkUs7HzAtdnPGjkzlHYW//YvncmTaO0fnMswJVLTKlMq9J/VnqLF1bH2CVYO9zBXIvf786SwgNrWAW/nmyOHE0kOzo79OVfm147qTPmF93ajwLWA814HUK8xpPZ5nMLgFaPpqlNO8co/5gpGm3cRrxRQ2yeOMCealz/EVJYS9LUmYugR42Ayg6iHLRoqwCKdtsjhMFZNEAOwsMs80='
